const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "https://media.istockphoto.com/photos/pancakes-with-berries-and-maple-syrup-picture-id161170090",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: "gujarati Thali",
    category: "lunch",
    price: 13.99,
    img: "https://imgmediagumlet.lbb.in/media/2019/12/5df8fe8c1d996cda1451ee58_1576599180189.jpg?fm=webp&w=750&h=500&dpr=1",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/1c/c2/29/eb/milo-godzilla.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "https://media-cdn.tripadvisor.com/media/photo-s/1a/36/d8/8e/hill-country-delight.jpg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://vishal-raj-1.github.io/Awesome-JavaScript-Projects/assets/Images/foodCourt/item-7.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "https://chindeep.com/wp-content/uploads/2016/12/oreoshake2DSC_0035.jpg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "https://64.media.tumblr.com/764cb060bc3f6c6d4d9fd38cdc1b4e91/tumblr_piukhbBYdY1wow359o1_1280.jpg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://image.shutterstock.com/shutterstock/photos/399586585/display_1500/stock-photo-traditional-american-lunch-close-up-399586585.jpg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "https://www.rachaelrayshow.com/sites/default/files/styles/1100x620/public/images/2018-07/91cf0815868e49fd91babbc6444805a4.jpg?itok=3M4EABTz",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: "quarantine buddy",
    category: "dinner",
    price: 16.99,
    img: "https://www.rachaelrayshow.com/sites/default/files/styles/1100x620/public/images/2018-07/91cf0815868e49fd91babbc6444805a4.jpg?itok=3M4EABTz",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
